# Generated by Django 5.0.4 on 2024-04-18 20:08

import apps.products.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images_url",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[apps.products.models.img_file_validation],
                verbose_name="image",
            ),
        ),
    ]
